version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: net.dv8tion:JDA
    versions:
    - 4.2.0_228
    - 4.2.0_229
    - 4.2.0_231
    - 4.2.0_232
    - 4.2.0_238
    - 4.2.0_240
    - 4.2.0_242
    - 4.2.0_246
    - 4.2.0_247
    - 4.2.1_254
    - 4.2.1_255
    - 4.2.1_256
    - 4.2.1_257
    - 4.2.1_259
    - 4.2.1_260
    - 4.2.1_261
  - dependency-name: com.sedmelluq:lavaplayer
    versions:
    - 1.3.67
    - 1.3.71
    - 1.3.72
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.1
  - dependency-name: org.mariadb.jdbc:mariadb-java-client
    versions:
    - 2.7.2
