version: '3'

services:
  moto-bot:
    image: docker.pkg.github.com/motoki317/moto-bot/moto-bot:master
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: moto-bot
      MYSQL_USER: moto-bot
      MYSQL_PASSWORD: password
      DISCORD_ACCESS_TOKEN: ${DISCORD_ACCESS_TOKEN}
      BOT_DISCORD_ID: ${BOT_DISCORD_ID}
      PLAYER_TRACKER_CHANNEL: ${PLAYER_TRACKER_CHANNEL}
      BOT_RESTART_CHANNEL: ${BOT_RESTART_CHANNEL}
      BOT_LOG_CHANNEL_0: ${BOT_LOG_CHANNEL_0}
      BOT_LOG_CHANNEL_1: ${BOT_LOG_CHANNEL_1}
      BOT_LOG_CHANNEL_2: ${BOT_LOG_CHANNEL_2}
      BOT_LOG_CHANNEL_3: ${BOT_LOG_CHANNEL_3}
      BOT_LOG_CHANNEL_4: ${BOT_LOG_CHANNEL_4}
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - internal
    volumes:
      - $HOME/.m2:/root/.m2

  mysql:
    image: mariadb:10.4.10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: moto-bot
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - internal
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

networks:
  internal:
