name: Release master

on:
  push:
    branches:
      - master

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/motoki317/moto-bot:master
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [image]
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@262770b68bf225871bf8219e01b27e5d78cf4a59
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy
        run: ssh -o LogLevel=QUIET -t ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "~/deploy.sh"
